version: 1
projectName: better-chatbot
type: docker-compose
composefile: docker-compose.yml
proxy: caddy # Explicitly set to use Caddy instead of Traefik
domain: chat.nexus-agency.net
environment:
  - NODE_ENV=production
  - NO_HTTPS=1
  - PORT=3000
  - POSTGRES_HOST=postgres
  - POSTGRES_PORT=5432
  - POSTGRES_DB=better_chatbot
  # Connection string for Drizzle
  - POSTGRES_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/better_chatbot
  # File storage configuration (use local filesystem instead of Vercel Blob)
  - FILE_STORAGE_TYPE=local
  - FILE_STORAGE_PREFIX=uploads
  - UPLOAD_STORAGE_PATH=/app/uploads
  - MAX_FILE_SIZE=104857600
  - ALLOWED_FILE_TYPES=.pdf,.doc,.docx,.txt,.jpg,.png,.gif,.md,.csv,.json,.yaml,.yml
  # App URL
  - BETTER_AUTH_URL=https://chat.nexus-agency.net
envFiles:
  - ./.env.docker
healthCheck:
  path: /api/health
  port: 3000
# Persistent volumes for file storage and database
volumes:
  - uploads_data:/app/uploads
  - postgres_data:/var/lib/postgresql/data
