version: 1
projectName: better-chatbot
type: docker-compose
composefile: docker-compose.yml
proxy: caddy # Explicitly set to use Caddy instead of Traefik
domain: chat.nexus-agency.net
environment:
  - NODE_ENV=production
  - NO_HTTPS=1
  - PORT=3000
  - POSTGRES_HOST=postgres
  - POSTGRES_PORT=5432
  - POSTGRES_DB=mcp_chat
  # Credentials will be set in Coolify environment variables
  # Connection string for Drizzle
  - POSTGRES_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/mcp_chat
  # App URL will be set in Coolify environment variables
envFiles:
  - ./.env
healthCheck:
  path: /api/health
  port: 3000
